### ISSUE TITLE
Some questions on setup and clarifications of the DNS service configuration

### ISSUE THREAD

**Issue by shankscoder** [jwhited/wgsd#1]
First off, thanks for the writeup.

I've been looking into how to establish direct peer to peer connections between nodes without a concentrator node, and this really helps.

I have a couple of questions on the configuration you've mentioned in your blog post.

1. When launching `wgsd-client` you're passing the parameter `-dns=4.4.4.4:5353`. But the zone record config earlier is mapped to `.:53`. Is this a typo, or is there something I missed about exposing the dns server on `5353`?

2.  If I'm understanding this right, the DNS server resolver port has to be publicly accessible to allow the clients to resolve the peer IPs. Is this correct?

~If yes, then is there a way to have it so that the DNS server is only available over the wireguard connection and therefore private to the nodes on the network? It would be more secure to ensure that node IP data is kept private to only those authorized to connect to the network.~

Sorry, I just re-read your post and you're asking these questions as well, so its redundant atm.

Will play around with this to see if we can get the resolver to work over the tunnel.

**Comment by jwhited** [comment]
You can use the [bind plugin](https://coredns.io/plugins/bind/) to force CoreDNS to listen on a particular address/interface. If `10.0.0.254` is your WireGuard interface, it would look something like this:

```
ubuntu@ip-172-31-26-195:~$ ifconfig wg0
wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 8921
        inet 10.0.0.254  netmask 255.255.255.255  destination 10.0.0.254
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 58476  bytes 2137520 (2.1 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2304  bytes 213336 (213.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
ubuntu@ip-172-31-26-195:~$ cat Corefile
.:53 {
  debug
  bind 10.0.0.254
  wgsd jordanwhited.net. wg0
}
ubuntu@ip-172-31-26-195:~$ sudo ./coredns
.:53 on 10.0.0.254
CoreDNS-1.6.9
linux/amd64, go1.14.2,
^C[INFO] SIGINT: Shutting down
```

Thanks for checking this out, hope it is helps you achieve what you're after.

**Comment by shankscoder** [comment]
Thanks.

So does this mean the client only queries CoreDNS after initial wireguard tonnel to `registry` is made? If that's the case, then this is solved.

**Comment by jwhited** [comment]
The queries will only route over the Wireguard tunnel, assuming everything is configured properly.
