### ISSUE TITLE
Using wgsd when registry is a DNS

### ISSUE THREAD

**Issue by HarvsG** [jwhited/wgsd#33]
I am interested in using wgsd to create a mesh between my wireguard nodes (I currently use a hub and spokes model).

The device I would like to use as the registry (my current hub) runs a PiHole DNS  Docker (port 53). Would this conflict with wgsd?

**Comment by cppohl** [comment]
Hi, I don't think this would be a problem. Just configure the CoreDNS server to run on a different port (e.g. 5353).

**Comment by HarvsG** [comment]
Thanks @cppohl
