### ISSUE TITLE
compilation with plugin coredns breaks

### ISSUE THREAD

**Issue by malaquias63** [jwhited/wgsd#7]
root@50a42f:~/core/coredns# go build
# github.com/jwhited/wgsd
/root/go/pkg/mod/github.com/jwhited/wgsd@v0.0.0-20200529024624-49e376d95c4b/setup.go:14:18: cannot use setup (type                                                                func(*"github.com/caddyserver/caddy".Controller) error) as type "github.com/coredns/caddy".SetupFunc in argument to                                                                plugin.Register
/root/go/pkg/mod/github.com/jwhited/wgsd@v0.0.0-20200529024624-49e376d95c4b/setup.go:45:21: cannot use c (type *"gi                                                               thub.com/caddyserver/caddy".Controller) as type *"github.com/coredns/caddy".Controller in argument to dnsserver.Get                                                               Config
root@50a42f:~/core/coredns#

used go lang 14 

some hint `?

**Comment by malaquias63** [comment]
and even with version coredns 1.6.0 i get

**Comment by tobikris** [comment]
I guess my issue was related: #5

**Comment by jwhited** [comment]
This was a backwards incompatible change in coreDNS 1.8.0: https://coredns.io/2020/09/21/coredns-1.8.0-release/

> The CoreDNS team has released CoreDNS-1.8.0.
>
> This release add two backwards incompatible changes.
>
> One, because Caddy is now developing a version 2 and we are using version 1 we’ve internalized Caddy into https://github.com/coredns/caddy. This means the caddy types change and all plugins need to fix the import path from: github.com/caddyserver/caddy to github.com/coredns/caddy (this can thankfully be automated).

I will version wgsd in its current form and provide a newer version that works with coreDNS v1.8.0

**Comment by jwhited** [comment]
fixed in https://github.com/jwhited/wgsd/commit/dfd8346f693d4ab17680afb4b488bb401d2afe45
